### ISSUE TITLE
cygwin problem

### ISSUE THREAD

**Issue by mhlaws** [datagrok/modular-git-hooks#2]
It appears to be set up correctly but basename $0 is returning dispatch instead of the symlink/hook name

[testHook](master)$ ./dispatch/install-dispatch
...
link   post-checkout -> dispatch
...

then later

[testHook](master)$ git checkout -- hooks/post-receive
'dispatch' should not be executed directly; instead, symlink a githook to it and let git invoke it.

works fine on linux -- but in cygwin basename $0 appears to be reading through the symlink and getting 'dispatch'.

i am wondering if there are any low impact changes I could make to it that would make it work both for cygwin and everywhere else.

**Comment by datagrok** [comment]
Hmm. Well, it strikes me as inelegant but on systems where `basename $0` results in `dispatch` we might copy the dispatch script into place rather than symlinking. I'll try to experiment with cygwin a bit to see if any other solutions strike me.

Thanks for the bug report!

**Comment by mhlaws** [comment]
I was experimenting with a separate install script just for cygwin that
contains two lines.  One that sets an environment variable and another that
calls the dispatch script (with a minor modification to check for the
environment variable).  Almost got it working..  Ran into another issue
where -f -a -x tests on cygwin symbolic links return false but it does
respond to -h.  My goal is for it to use as much of the unmodified dispatch
script as possible.  Once I have that working I will make sure it works on
mingw as well (as those on my team that dont use cygwin use mingw git bash).

Great project!

**Comment by datagrok** [comment]
@mhlaws I'm having some trouble reproducing the issue you reported, and the `basename $0` behavior you describe:

    IEUser@IE11Win10 /cygdrive/c/Users/IEUser/Desktop/deleteme
    $ ls -l
    total 1
    lrwxrwxrwx 1 IEUser None 20 Mar 22 19:49 nottest -> /home/IEUser/test.sh
    
    IEUser@IE11Win10 /cygdrive/c/Users/IEUser/Desktop/deleteme
    $ cat /home/IEUser/test.sh
    #!/bin/sh
    
    echo `basename $0`
    
    IEUser@IE11Win10 /cygdrive/c/Users/IEUser/Desktop/deleteme
    $ ./nottest
    nottest

Can you tell me more about the system you're running? Is the filesystem that underlies your Cygwin installation NTFS, Fat32, or something else? Which version of Windows? Which version of Cygwin?

Can you also describe your directory layout a bit? E.g. does it look like this?

    ./testHook - a git clone containing your collection of hooks
    ./testHook/hooks/post-receive - a directory containing some post-receive hooks
    ./testHook/dispatch - a git clone of this project

**Comment by mhlaws** [comment]
That is what my directory layout looks like.
cygwin version is 1.7.35
windows version is 7 SP1
hard disk is formatted NTFS

Thanks for looking into the issue!

**Comment by datagrok** [comment]
This is super old, but I got some time with a Windows box and took another look.

It looks like the symlink-related problems you experienced were due to [a Cygwin bug](https://cygwin.com/ml/cygwin/2015-03/msg00270.html) that has been fixed in the latest version, 2.0.0. I did some experiments myself under Cygwin 2.0.0, Windows 7 SP1, NTFS, and can't reproduce the problem.

I appreciate the report and the patch (with installer!) that you wrote, but I'm reluctant to include what is essentially a workaround for a bug fixed upstream. Is it possible for you to upgrade to the latest version of Cygwin? If not I'll consider merging your improvements.

**Comment by mhlaws** [comment]
I appreciate your help in looking into this issue.
I will investigate to see if this fixes my problem.

**Comment by mhlaws** [comment]
Updating cygwin to version 2.0.0 fixes the problem!
However, the problem still exists with msysgit 1.9.5 which is based on an old version of cygwin.
Anyone using the current version of Git Bash from git-scm.com would be unable to use dispatch.

The following works in cygwin 2.0.0 but gives the following error in Git Bash / msysgit 1.9.5:
error: cannot spawn .git/hooks/pre-commit: No such file or directory

According to msysgit's documentation: 
"..., MSys ships with a POSIX layer (based on an old version of Cygwin)"
I do not know if they would be amenable to updating their cygwin to allow symbolic links.

**Comment by mhlaws** [comment]
Next release of git for windows will be on a new environment.  
it is switching from msysgit/mysysgit to git-for-windows/git

I tested with the developer preview:
$ git --version
git version 2.3.7.windows.1

(the old one said git version 1.9.5.msysgit.0)

$ git commit -m 'test'
error: cannot spawn .git/hooks/pre-commit: No such file or directory

Looks like the next version actively being developed has the same issue.

**Comment by mhlaws** [comment]
Testing between the three versions I realized my previous test did not re-run the install-dispatch script each time.  Once this step was done, mysysgit 1.9.5 still doesn't work.. but git-for-windows 2.3.7 works!

**Comment by datagrok** [comment]
@mhlaws thank you so much for all the testing and investigation you did on this issue.
